### ISSUE TITLE
Trouble with installation - do I need to build the plugin?

### ISSUE THREAD

**Issue by cayd** [gotson/csvy#1]
Hi, 

I am new to Launchy and .NET I'm having trouble getting this plugin to work. The installation instructions seem to imply that I can copy everything into my Launchy folder and the plugin will just work, but I found that CSVy is not listed in the available plugins after doing so. I think instead I need a dll, but I cannot find one in the repository or elsewhere. That implies to me that I have to build it myself? If so, are there instructions for how to do it? I have not been able to after fiddling with Visual Studio for a while.

Thanks!

**Comment by gotson** [comment]
How about https://github.com/gotson/csvy/releases/tag/1.3.1 ?

**Comment by gotson** [comment]
You also need to install https://github.com/kshahar/launchysharp first

**Comment by cayd** [comment]
That is it, thank you. I didn't understand how releases work and I was looking in the code folder. Thanks again!
